name: Rust-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
          version: '0.14.2'
          args: '--ignore-tests --all-features -- --test-threads 1'
    - uses: codecov/codecov-action@v1.0.13
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        fail_ci_if_error: false
        verbose: true
